import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>William S L</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full">
        <div className="flex flex-col justify-center items-center h-full">
          <div className="">
            <h1 className="text-6xl font-bold tracking-widest">
              William Suarez
            </h1>
            <p className="text-lg text-blue-400 font-bold italic tracking-wide ml-1">
              Lumbantobing
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
